services:
  backend:
    image: rudnam/rudnote-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rudnote_db
      SPRING_DATASOURCE_USERNAME: rudnote_user
      SPRING_DATASOURCE_PASSWORD: rudnote_pass
    depends_on:
      - db
    networks:
      - app
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: rudnote_db
      POSTGRES_USER: rudnote_user
      POSTGRES_PASSWORD: rudnote_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rudnote_user -d rudnote_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    image: rudnam/rudnote-frontend:latest
    environment:
      - VITE_API_URL=/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app
    restart: unless-stopped

  caddy:
    image: rudnam/rudnote-caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app
    restart: unless-stopped

volumes:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  app:
