name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Run unit tests
        run: npm run test

  test-e2e:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    needs: test-frontend
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies and Playwright browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Start backend and db with docker compose
        run: docker compose up -d backend db

      - name: Wait for backend health check
        run: |
          for i in {1..15}; do
            status=$(curl -s http://localhost:8080/actuator/health | jq -r .status || echo "DOWN")
            if [ "$status" = "UP" ]; then
              echo "Backend is ready"
              exit 0
            fi
            echo "Waiting for backend to be ready ($i/15)..."
            sleep 4
          done
          echo "Backend did not become ready in time."
          docker compose logs backend || true
          exit 1

      - name: Run Playwright tests with retries
        run: npx playwright test --retries=2 --reporter=list,json

      - name: Upload Playwright test report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30


  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: rudnote_db
          POSTGRES_USER: rudnote_user
          POSTGRES_PASSWORD: rudnote_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready -U rudnote_user -d rudnote_db
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Wait for DB to be ready
        run: |
          for i in {1..15}; do
            if docker exec $(docker ps -qf "name=db") pg_isready -U rudnote_user -d rudnote_db; then
              echo "Database is ready"
              exit 0
            fi
            echo "Waiting for database to be ready ($i/15)..."
            sleep 4
          done
          echo "Database did not become ready in time."
          docker logs $(docker ps -qf "name=db") || true
          exit 1

      - name: Run tests with Maven
        run: ./mvnw clean verify -DskipTests=false -Dmaven.test.failure.ignore=false

  docker-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend, test-e2e]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: rudnam/rudnote-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          build-args: |
            VITE_API_URL=/api
          tags: rudnam/rudnote-frontend:latest

      - name: Build and push caddy
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.caddy
          push: true
          tags: rudnam/rudnote-caddy:latest
